name: Deploy danieldoescode to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DDC_HOST }}         # EC2 public IP or hostname
          username: ${{ secrets.DDC.USER }}       # e.g., "ec2-user" or "ubuntu"
          key: ${{ secrets.DDC_SSH_KEY }}         # Your private SSH key (set in GitHub Secrets)
          script: |
            # Change to your repository directory on EC2
            cd ~/danieldoescode

            # Pull the latest changes from the main branch
            git pull origin main

            # Build a new Docker image using the Dockerfile in the repository
            docker build -t danieldoescode:latest .

            # Stop and remove the current running container, if any
            docker stop danieldoescode-container || true
            docker rm danieldoescode-container || true

            # Run a new container mapping host port 8080 to container port 80
            docker run -d -p 8080:80 --name danieldoescode-container danieldoescode:latest
